-- MySQL Script generated by MySQL Workbench
-- Sat Jan 27 23:06:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema videos_management_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema videos_management_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `videos_management_system` DEFAULT CHARACTER SET utf8 ;
USE `videos_management_system` ;

-- -----------------------------------------------------
-- Table `videos_management_system`.`videos_management_persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videos_management_system`.`videos_management_persons` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `birthdate` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videos_management_system`.`videos_management_videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videos_management_system`.`videos_management_videos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `author_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `url` VARCHAR(2000) NOT NULL,
  `file` VARCHAR(300) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE,
  UNIQUE INDEX `file_UNIQUE` (`file` ASC) VISIBLE,
  INDEX `fk_videos_management_videos_videos_management_persons1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_management_videos_videos_management_persons1`
    FOREIGN KEY (`author_id`)
    REFERENCES `videos_management_system`.`videos_management_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videos_management_system`.`videos_management_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videos_management_system`.`videos_management_comments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT UNSIGNED NOT NULL,
  `video_id` BIGINT UNSIGNED NOT NULL,
  `contents` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videos_management_comments_videos_management_videos1_idx` (`video_id` ASC) VISIBLE,
  INDEX `fk_videos_management_comments_videos_management_persons1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_management_comments_videos_management_videos1`
    FOREIGN KEY (`video_id`)
    REFERENCES `videos_management_system`.`videos_management_videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videos_management_comments_videos_management_persons1`
    FOREIGN KEY (`person_id`)
    REFERENCES `videos_management_system`.`videos_management_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videos_management_system`.`videos_management_collaborators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videos_management_system`.`videos_management_collaborators` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT UNSIGNED NOT NULL,
  `video_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videos_management_collaborators_videos_management_person_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_videos_management_collaborators_videos_management_videos_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_management_collaborators_videos_management_persons1`
    FOREIGN KEY (`person_id`)
    REFERENCES `videos_management_system`.`videos_management_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videos_management_collaborators_videos_management_videos1`
    FOREIGN KEY (`video_id`)
    REFERENCES `videos_management_system`.`videos_management_videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videos_management_system`.`videos_management_reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videos_management_system`.`videos_management_reviews` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT UNSIGNED NOT NULL,
  `video_id` BIGINT UNSIGNED NOT NULL,
  `rating` TINYINT NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videos_management_reviews_videos_management_persons1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_videos_management_reviews_videos_management_videos1_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_management_reviews_videos_management_persons1`
    FOREIGN KEY (`person_id`)
    REFERENCES `videos_management_system`.`videos_management_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videos_management_reviews_videos_management_videos1`
    FOREIGN KEY (`video_id`)
    REFERENCES `videos_management_system`.`videos_management_videos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `videos_management_system`.`videos_management_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `videos_management_system`.`videos_management_users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT UNSIGNED NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_videos_management_users_videos_management_persons1_idx` (`person_id` ASC) VISIBLE,
  UNIQUE INDEX `person_id_UNIQUE` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_management_users_videos_management_persons1`
    FOREIGN KEY (`person_id`)
    REFERENCES `videos_management_system`.`videos_management_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
